In [52]:
import pandas as pd
import numpy as np

In [6]:
# Q1. Pandas version
# What's the version of Pandas that you installed?
pd.__version__

'2.3.1'

In [ ]:
# Q2. Records count
# How many records are in the dataset?

In [1]:
data = ' https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv'

In [7]:
# !wget $data

In [4]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [8]:
len(df)

9704

In [10]:
# Q3. Fuel types
# How many fuel types are presented in the dataset?
df.fuel_type.nunique()

2

In [61]:
# Q4. Missing values
# How many columns in the dataset have missing values?
nmiss = df.isnull().sum()
nmiss[nmiss > 0].count()

np.int64(4)

In [88]:
# Q5. Max fuel efficiency
df[df.origin == "Asia"].fuel_efficiency_mpg.max()

np.float64(23.76)

In [142]:
# Q6. Median value of horsepower
# 1. Find the median value of horsepower column in the dataset.
df.horsepower.median()

np.float64(152.0)

In [92]:
# 2. Next, calculate the most frequent value of the same horsepower column.
df.horsepower.mode()

0    152.0
Name: horsepower, dtype: float64

In [105]:
# 3. Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
df.horsepower = df.horsepower.fillna(152)

In [108]:
# 4. Now, calculate the median value of horsepower once again.
df.horsepower.median()

np.float64(152.0)

In [118]:
# Q7. Sum of weights
# 1. Select all the cars from Asia
asia_cars = df[df.origin == 'Asia']
# asia_cars

In [123]:
# 2. Select only columns vehicle_weight and model_year
# 3. Select the first 7 values
first_seven = asia_cars[['vehicle_weight', 'model_year']][0:7]
first_seven

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [127]:
# 4. Get the underlying NumPy array. Let's call it X.
X = np.array(first_seven)
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [131]:
# 5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X.T @ X
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [132]:
# 6. Invert XTX
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [137]:
# 7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [139]:
# 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inverse @ X.T @ y
w

array([0.01386421, 0.5049067 ])

In [141]:
# 9. What's the sum of all the elements of the result?
w.sum()

np.float64(0.5187709081074016)